# Generated by Django 4.2.7 on 2023-11-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sana', models.DateField()),
                ('matn', models.TextField()),
                ('mediya', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
