# Generated by Django 4.2.7 on 2023-11-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='mediya',
            new_name='media',
        ),
    ]
